/// Flutter icons MyFlowApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlowApp
///      fonts:
///       - asset: fonts/MyFlowApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlowApp {
  MyFlowApp._();

  static const _kFontFam = 'MyFlowApp';
  static const IconData rho = const IconData(0x3c1, fontFamily: _kFontFam);
  static const IconData Z = const IconData(0x5a, fontFamily: _kFontFam);
  static const IconData temperature = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData tumblr = const IconData(0xf173, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xf219, fontFamily: _kFontFam);
}
